### ISSUE TITLE
Migrate to Polymer 1.x.x

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-markdown-tabbededitor#1]

**Comment by joeblew99** [comment]
Me too please.

This is a very useful component.

Btw when I try the live demo on mobile chrome on android it does not render properky. There are no tabs and the content displays without the editor.

**Comment by warpech** [comment]
Closing as won't fix. We have decided to deprecate this repo. See the deprecation announcement at #6.

Sorry for that @joeblew99. I believe it should be possible to use a combination of custom elements in your app to replicate the feature set of this element.
