### ISSUE TITLE
remove .bowerrc (use polyserve instead)

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-markdown-tabbededitor#4]
This repo uses `.bowerrc` file which causes it to act arcane - when you type `bower install`, the dependencies get installed in the parent directory.

Proposed solution - remove `.bowerrc` and recommend using `polyserve`. 

Same thing was done in https://github.com/Juicy/juicy-select/pull/8

**Comment by Mihaiii** [comment]
Closing as done.
